from typing import Optional, Union, Tuple, Any, Dict, List
from astropy.table import QTable

def load_query(file: str) -> QTable: ...

def get_kwargs(names: Tuple[str, ...], default: Any, kwargs: Dict[str, Any]) -> Any: ...

def get_file_list(
    tn: Optional[str] = None, fold: Optional[str] = None, key: Optional[str] = None
) -> List[str]: ...

def tnlist(gc_name: str) -> List[str]: ...

def _timestamp() -> str: ...

def _findTracknum(tn: str, complete_path: bool = False) -> Union[str, List[str]]: ...
